# This file is added alongside nginx.conf

location /livekit/jwt/ {
    proxy_pass http://127.0.0.1:__PORT_LIVEKIT_JWT__/;
    include proxy_params_no_auth;
    more_set_headers "Access-Control-Allow-Origin: *";
}

location /livekit/sfu/ {
    proxy_pass http://127.0.0.1:__PORT_LIVEKIT__/;
    include proxy_params_no_auth;
}
