#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

federation="true"
registration_token=$(ynh_string_random --length=27)

ynh_app_setting_set --key=federation --value=$federation
ynh_app_setting_set --key=registration_token --value=$registration_token

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R $app:root "$install_dir"
chmod +x "$install_dir/tuwunel"

#=================================================
# INSTALL COTURN IF NOT INSTALLED
#=================================================
# Credit to: https://github.com/YunoHost-Apps/prosody_ynh/blob/testing/scripts/install#L15C1-L22C79
if [ $calls_enabled -eq 1 ]; then
    if ! yunohost app list | grep -q "id: coturn"; then
            echo "Coturn is not installed. Installing... "
            yunohost tools update
            yunohost app install coturn --force --args "domain=$domain"
    fi

    turn_password=$(ynh_app_setting_get --app="coturn" --key=turnserver_pwd)
    turn_external_port=$(ynh_app_setting_get --app="coturn" --key=port_turnserver_tls)
    turn_domain=$(ynh_app_setting_get --app="coturn" --key="domain")
fi

#=================================================
# SETUP LIVEKIT FOR CALLS
#=================================================
if [ $calls_enabled -eq 1 ]; then
    ynh_app_setting_set_default --key=livekit_secret --value="$(ynh_string_random --length=40)"

    # Install livekit jwt
    ynh_setup_source --source_id=lk_jwt --dest_dir="$install_dir/lk_jwt"

    chmod +x "$install_dir/lk_jwt/lk-jwt-service"
    chown "$app" -R "$install_dir"

    # Install livekit server for element-call
    ynh_setup_source --source_id=livekit --dest_dir="$install_dir/livekit"

    # Setup services and config files
    get_lk_node_ip
    ynh_config_add_systemd --service="$app"-livekit --template=$app-livekit.service
    ynh_config_add_systemd --service="$app"-lk-jwt --template=$app-lk-jwt.service

    ynh_config_add --template=livekit.yml --destination=$install_dir/livekit/livekit.yml
    ynh_config_add --template=lk-jwt.conf --destination=$install_dir/lk_jwt/lk-jwt.conf

    yunohost service add "$app"-livekit --description 'Livekit server for element call.'
    yunohost service add "$app"-lk-jwt --description 'RTC Livekit JWT service for element call.'

    ynh_systemctl --service="$app"-livekit.service --action="start"
    ynh_systemctl --service="$app"-lk-jwt.service --action="start"
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create .well-known redirection for access by federation
if yunohost --output-as plain domain list | grep -q "^$server_name$"
then
    if [ $calls_enabled -eq 1 ]; then
        ynh_config_add --template="server_name_livekit.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
        ynh_config_add --template="nginx_livekit.conf" --destination="/etc/nginx/conf.d/${domain}.d/${app}_livekit.conf"
    else
        ynh_config_add --template="server_name.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
    fi
fi

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Chat server powered by Matrix" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="tuwunel.toml" --destination="$install_dir/tuwunel.toml"

chmod 400 "$install_dir/tuwunel.toml"
chown $app:root "$install_dir/tuwunel.toml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
