#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

if [ $calls_enabled -eq 1 ]; then
    yunohost service remove "$app"-livekit
    yunohost service remove "$app"-lk-jwt

    ynh_config_remove_systemd "$app"-livekit
    ynh_config_remove_systemd "$app"-lk-jwt

    ynh_safe_rm "/etc/nginx/conf.d/${domain}.d/${app}_livekit.conf"
fi

ynh_config_remove_nginx

ynh_safe_rm "/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
