#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# If unset, set $calls_enabled as false (0)
ynh_app_setting_set_default --app="$app" --key=calls_enabled --value=0

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

if [ $calls_enabled -eq 1 ]; then
    ynh_systemctl --service="$app"-livekit.service --action=stop
    ynh_systemctl --service="$app"-lk-jwt.service --action=stop
fi

#=================================================
# FETCH VARIABLES FOR CONFIG
#=================================================
turn_password=$(ynh_app_setting_get --app="coturn" --key=turnserver_pwd)
turn_external_port=$(ynh_app_setting_get --app="coturn" --key=port_turnserver_tls)
turn_domain=$(ynh_app_setting_get --app="coturn" --key=domain)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="tuwunel.toml"

chown -R $app:root "$install_dir"
chmod +x "$install_dir/tuwunel"

if [ $calls_enabled -eq 1 ]; then
    ynh_app_setting_set_default --key=livekit_secret --value="$(ynh_string_random --length=40)"

    # Install livekit jwt
    ynh_setup_source --source_id=lk_jwt --dest_dir="$install_dir/lk-jwt-service"

    chmod +x "$install_dir/lk-jwt-service"
    chown "$app" -R "$install_dir"

    # Install livekit server for element-call
    ynh_setup_source --source_id=livekit --dest_dir="$install_dir/livekit"
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

# Create .well-known redirection for access by federation
if yunohost --output-as plain domain list | grep -q "^$server_name$"
then
    if [ $calls_enabled -eq 1 ]; then
        ynh_config_add --template="server_name_livekit.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
        ynh_config_add --template="nginx_livekit.conf" --destination="/etc/nginx/conf.d/${domain}.d/${app}_livekit.conf"
    else
        ynh_config_add --template="server_name.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
    fi
fi

ynh_config_add_systemd

yunohost service add $app --description="Chat server powered by Matrix" --log="/var/log/$app/$app.log"

if [ $calls_enabled -eq 1 ]; then
    yunohost service add "$app"-livekit --description 'Livekit server for element call.'
    yunohost service add "$app"-lk-jwt --description 'RTC Livekit JWT service for element call.'

    get_lk_node_ip
    ynh_config_add_systemd --service="$app"-livekit --template=$app-livekit.service
    ynh_config_add_systemd --service="$app"-lk-jwt --template=$app-lk-jwt.service
fi

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

#ynh_config_add --template="tuwunel.toml" --destination="$install_dir/tuwunel.toml"

if [ $calls_enabled -eq 1 ]; then
    ynh_config_add --template=livekit.yml --destination=$install_dir/livekit/livekit.yml
    ynh_config_add --template=lk-jwt.conf --destination=$install_dir/lk-jwt.conf
fi

chmod 400 "$install_dir/tuwunel.toml"
chown $app:$app "$install_dir/tuwunel.toml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

if [ $calls_enabled -eq 1 ]; then
    ynh_systemctl --service="$app"-livekit.service --action=restart
    ynh_systemctl --service="$app"-lk-jwt.service --action=restart
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
